package org.fedorahosted.freeotp.ui;

const val READ_JSON_REQUEST_CODE = 42
const val WRITE_JSON_REQUEST_CODE = 43
const val READ_KEY_URI_REQUEST_CODE = 44
const val WRITE_KEY_URI_REQUEST_CODE = 45
const val ADD_TOKEN_REQUEST_CODE = 46
const val SCAN_TOKEN_REQUEST_CODE = 47
const val EDIT_TOKEN_REQUEST_CODE = 48
const val DELETE_TOKEN_REQUEST_CODE = 48
