object Versions {
    const val KOTLIN = "1.5.30"
    const val HILT = "2.38.1"
    const val APP_COMPAT = "1.3.1"
    const val ACTIVITY_KTX = "1.3.1"
    const val MATERIAL = "1.4.0"
    const val CORE_KTX = "1.6.0"
    const val KOTLINX_COROUTINES = "1.5.1"
    const val LIFECYCLE_KTX = "2.3.1"
    const val CAMERAX = "1.0.1"
    const val CAMERAX_VIEW = "1.0.0-alpha27"
    const val BIOMETRIC = "1.1.0"
    const val ZXING = "3.3.3"
    const val GSON = "2.8.7"
    const val GLIDE = "4.12.0"
    const val ROOM = "2.3.0"
    const val ANDROIDX_TEST_CORE = "1.3.0"
    const val ANDROIDX_JUNIT = "1.1.2"
    const val ANDROIDX_TRUTH = "1.3.0"
    const val ESPRESSO = "3.4.0"
}

