object Versions {
    const val KOTLIN = "1.6.10"
    const val HILT = "2.41"
    const val APP_COMPAT = "1.4.1"
    const val ACTIVITY_KTX = "1.4.0"
    const val MATERIAL = "1.5.0"
    const val CORE_KTX = "1.7.0"
    const val KOTLINX_COROUTINES = "1.6.0"
    const val LIFECYCLE_KTX = "2.4.1"
    const val CAMERAX = "1.1.0"
    const val BIOMETRIC = "1.1.0"
    const val ZXING = "3.3.3"
    const val GSON = "2.9.0"
    const val GLIDE = "4.13.1"
    const val ROOM = "2.4.0"
    const val ANDROIDX_TEST_CORE = "1.4.0"
    const val ANDROIDX_JUNIT = "1.1.3"
    const val ANDROIDX_TRUTH = "1.4.0"
    const val ESPRESSO = "3.4.0"
}

